root = "."

[build]
  binary = "."

[[watcher]]
  paths = ["."]

  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[runner]
  binary = "./{{.Dir}}"

  args = [
    "-arg1",
    "value1",
    "-arg2",
    "value2"
  ]
